"""Regenerate src/pandas3_ready/names.py: attribute names that exist on DataFrame/Series/Index in the pandas versions given.

usage: python tools/gen_names.py PYTHON_A PYTHON_B > src/pandas3_ready/names.py   (interpreters that have pandas 2.3.x and 3.0.x installed)
A column access like `df.price` is only treated as a column when the name is not one of these."""
import subprocess
import sys

CODE = "import pandas as pd;print('\\n'.join(sorted(set(dir(pd.DataFrame))|set(dir(pd.Series))|set(dir(pd.Index)))))"
names = set()
for py in sys.argv[1:]:
    names |= set(subprocess.run([py, "-c", CODE], capture_output=True, text=True, check=True).stdout.split())
print('"""Generated by tools/gen_names.py from pandas 2.3.x and 3.0.x (union of dir() of DataFrame, Series and Index). Do not edit."""')
print("PANDAS_ATTRS = frozenset({")
for n in sorted(names):
    print(f"    {n!r},")
print("})")
